options:
  puppet-version:
    type: int
    default: 3 
    description: |
      Puppet version choices are `3` or `4`.
  pin-puppet:
    type: string
    default: ''
    description: |
      This will override the system default for the
      general version of puppet specified by the 
      puppet-version config parameter.
  environment:
    type: string
    default: production
    description: |
      Puppet environment.
  puppet-server:
    type: string
    default: ''
    description: |
      Puppetmaster fqdn.
  ca-server:
    type: string
    default: ''
    description: |
      Puppet ca-server fqdn.
  auto-start:
    type: boolean
    default: true
    description: |
      Set puppet agent auto-start, defaults to true.
  puppet-gpg-id:
    type: string
    default: 4BD6EC30
    description: |
      Puppetlabs gpg-key id.
  package_status:
    default: "hold"
    type: string
    description: >
        The status of service-affecting packages will be set to this
        value in the dpkg database. Valid values are "install" and "hold".
